version: '3.3'
services:

  user-service:
    image: sebczu/personal:${USER_VERSION}
    container_name: user-container
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOSTNAME=mysql
      - DATABASE_PORT=3306
      - DATABASE_SCHEMA=user
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=pass

  user-sql-updater:
    image: sebczu/personal:${USER_SQL_UPDATER_VERSION}
    container_name: user-sql-updater
    environment:
      - DATABASE_HOSTNAME=mysql
      - DATABASE_PORT=3306
      - DATABASE_SCHEMA=user
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=pass

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./volumes:/docker-entrypoint-initdb.d