name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run container and integration tests
      run: >
        mvn -B post-integration-test
        -Plocal-build
        -Pintegration-test
        -Djib.from.auth.username=${{ secrets.DOCKERHUB_USERNAME }}
        -Djib.from.auth.password=${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Deploy docker image
      run: >
        mvn -B package
        -Pregistry-build
        -DskipTests
        -Djib.from.auth.username=${{ secrets.DOCKERHUB_USERNAME }}
        -Djib.from.auth.password=${{ secrets.DOCKERHUB_PASSWORD }}
        -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }}
        -Djib.to.auth.password=${{ secrets.DOCKERHUB_PASSWORD }}

